app <- ShinyDriver$new("../../")
app$snapshotInit("test_trans")

# Fix cf.

Sys.sleep(3)
app$snapshot()
app$setInputs(`standalone-data_tabs` = "Visits")
app$snapshot()
app$setInputs(`standalone-data_tabs` = "Movements")
app$snapshot()
app$setInputs(`standalone-data_tabs` = "Presence")
app$snapshot()
app$setInputs(`standalone-data_tabs` = "Displacements")
app$snapshot()
app$setInputs(`standalone-data_tabs` = "Activity")
app$snapshot()
app$setInputs(`standalone-data_tabs` = "Daily activity")
app$snapshot()
app$setInputs(`standalone-data_tabs` = "log")
app$snapshot()
app$setInputs(main = "Settings")
app$snapshot()
app$setInputs(`standalone_trans-set_visits_bw` = 10000)
app$setInputs(`standalone_trans-settings_get` = "click")
app$snapshot()
app$setInputs(main = "Transformations")
app$setInputs(`standalone-data_tabs` = "Visits")
app$snapshot()
app$setInputs(`standalone-data_tabs` = "log")
app$snapshot()
